spring:
  datasource:
    url: jdbc:mysql://192.168.99.101:30002/product_schema
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: none
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl