spring:
  rabbitmq:
    host: 192.168.99.101
    port: 31730
    username: dev
    password: dev

  datasource:
    url: jdbc:mysql://192.168.99.101:30002/customer_schema
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: none
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

order:
  exchange: order-exchange
  queue: order-queue
  routingkey: order

