apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
     containers:
       - name: customer
         image: customer:latest
         imagePullPolicy: Never
         ports:
           - containerPort: 7070