spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: http://localhost:6060/
          predicates:
            - Path=/product/**
        - id: customer_route
          uri: http://localhost:7070/
          predicates:
            - Path=/customer/**


management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5050